In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from sklearn.datasets import load_iris
import numpy as np

In [9]:
iris = load_iris()

In [10]:
X = iris["data"]
y = iris["target"]

In [11]:
X[:10]
y[:10]
np.unique(y)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 1, 2])

In [12]:
class Kmeans():
    def __init__(self, k=3):
        self.k = k
        
    def forward(self, X):
        init_index = np.random.choice(X.shape[0], self.k, replace = False)
        distance = np.zeros((X.shape[0], self.k))
        cluster = np.zeros(X.shape[0])
        centres = X[init_index]
        c = 0
        count = 0
        while(1):
            count+=1
            old_one = np.array(centres, copy = True)
            
            for i, centre in enumerate(centres):
                distance[:, i] = np.sqrt(np.sum(pow((X-centre), 2), axis=1))

            cluster = np.argmin(distance, axis=1)

            for i in range(self.k):
                centres[i, :] = np.mean(X[cluster == i, :], axis=0)

            if np.array_equal(old_one, centres):
                c+=1
                if c==3:
                    print("총 ")
                    return cluster
            else:
                c=0

In [13]:
kmeans = Kmeans(k=3)
result = kmeans.forward(X)

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, result)

array([[ 0, 50,  0],
       [47,  0,  3],
       [14,  0, 36]], dtype=int64)

In [15]:
n = 3
index = np.random.choice(X.shape[0], n, replace = False)
X[index]

array([[5. , 2. , 3.5, 1. ],
       [6.6, 3. , 4.4, 1.4],
       [5.5, 3.5, 1.3, 0.2]])

In [ ]:
a = X[index]

In [ ]:
distance = np.zeros((150,4))
for i, centre in enumerate(X[index]):
    distance[:,i] = np.sqrt(np.sum(pow((X-centre), 2), axis=1))

In [ ]:
distance[:,3] = np.argmin(distance[:,:3], axis=1)